const X_API_TOKEN = "Your API Token";

function persianToFinglish(persianText) {
  const charMap = {
    آ: "A",
    ا: "A",
    ب: "B",
    پ: "P",
    ت: "T",
    ث: "S",
    ج: "J",
    چ: "Ch",
    ح: "H",
    خ: "Kh",
    د: "D",
    ذ: "Z",
    ر: "R",
    ز: "Z",
    ژ: "Zh",
    س: "S",
    ش: "Sh",
    ص: "S",
    ض: "Z",
    ط: "T",
    ظ: "Z",
    ع: "A",
    غ: "Gh",
    ف: "F",
    ق: "Q",
    ک: "K",
    گ: "G",
    ل: "L",
    م: "M",
    ن: "N",
    و: "o",
    ه: "H",
    ی: "Y",
    ئ: "e",
    " ": "-",
  };

  const multiCharMap = {
    آذر: "azar",
    شهر: "shahr",
    امید: "omid",
    رود: "roud",
    اهواز: "ahvaz",
    شر: "shar",
    غر: "ghar",
    خراسان: "khorasane",
    جنوبی: "jonobi",
    رضوی: "razavi",
    شمالی: "shomali",
    جدید: "jadid",
    پیشوا: "pishva",
    منیر: "monir",
    اسلام: "islam",
    دولت: "dolat",
    رحمت: "rahmat",
    رستم: "rostam",
    رضوان: "rezvan",
    بابل: "babol",
    جمعه: "jome",
    کرد: "kurd",
    تبریز: "tabriz",
    تجریش: "tajrish",
    تخت: "takht",
    سلیمان: "soleyman",
    رویان: "royan",
    زرین: "zarin",
    زنگی: "zangi",
    کوه: "koh",
    زرد: "zard",
    تربت: "torbat",
    ترک: "turk",
    ویه: "vieh",
    توپ: "top",
    کر: "ker",
    صفا: "safa",
    بندر: "bandar",
    چهار: "chahar",
    چمن: "chaman",
    حبیب: "habib",
    حسن: "hasan",
    حسین: "hossein",
    حمید: "hamid",
    بهار: "bahar",
    سوار: "savar",
    دشت: "dasht",
    سلطان: "soltan",
    بهمن: "bahman",
    زهرا: "zahra",
    سفید: "sefid",
    پر: "par",
    پل: "pol",
    اص: "es",
    ها: "ha",
    ربز: "borz",
    سرد: "sard",
    ای: "i",
    بخ: "bakh",
    آذ: "Az",
    ته: "Teh",
    خو: "Kh",
    گو: "G",
    چو: "Ch",
    پو: "P",
    بو: "bu",
    جو: "J",
    شو: "Sh",
    سو: "S",
    زو: "Z",
    رو: "R",
    دو: "D",
    ذو: "Z",
    طو: "T",
    ظو: "Z",
    عو: "A",
    غو: "Gh",
    فو: "F",
    قو: "Q",
    کو: "K",
    لو: "L",
    مو: "M",
    نو: "N",
    هو: "H",
    یو: "Y",
    به: "Be",
    که: "Ke",
    گه: "Ge",
    چه: "Che",
    په: "Pe",
    جه: "Je",
    شه: "She",
    سه: "Se",
    زه: "Ze",
    ره: "Re",
    ده: "De",
    ذه: "Ze",
    طه: "Te",
    ظه: "Ze",
    عه: "Ae",
    غه: "Ghe",
    فه: "Fe",
    قه: "Ghe",
    له: "Le",
    مه: "Me",
    نه: "Ne",
    هه: "He",
    تو: "to",
    یه: "Ye",
    بی: "Bi",
    کی: "Ki",
    گی: "Gi",
    چی: "Chi",
    پی: "Pi",
    جی: "Ji",
    شی: "Shi",
    سی: "Si",
    زی: "Zi",
    ری: "Ri",
    دی: "Di",
    ذی: "Zi",
    طی: "Ti",
    ظی: "Zi",
    عی: "Ai",
    غی: "Ghi",
    فی: "Fi",
    قی: "Qi",
    کی: "Ki",
    لی: "Li",
    می: "Mi",
    نی: "Ni",
    هی: "Hi",
    یی: "Yi",
    با: "Ba",
    کا: "Ka",
    گا: "Ga",
    چا: "Cha",
    پا: "Pa",
    جا: "Ja",
    شا: "Sha",
    سا: "Sa",
    زا: "Za",
    را: "Ra",
    دا: "Da",
    ذا: "Za",
    طا: "Ta",
    ظا: "Za",
    عا: "Aa",
    غا: "Gha",
    فا: "Fa",
    قا: "Qa",
    کا: "Ka",
    لا: "La",
    ما: "Ma",
    نا: "Na",
    ها: "Ha",
    یا: "Ya",
  };

  // Replace multi-character sequences
  for (let key in multiCharMap) {
    persianText = persianText.replace(new RegExp(key, "g"), multiCharMap[key]);
  }

  // Replace individual characters
  let finglishText = "";
  for (let char of persianText) {
    finglishText += charMap[char] || char;
  }

  return finglishText.toLowerCase();
}

module.exports = {
  X_API_TOKEN: X_API_TOKEN,
  persianToFinglish: persianToFinglish,
};
